### ISSUE TITLE
Membership expiration dates are not displaying.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/points-and-rewards-for-woocommerce#147]
**Bug Name -** Membership expiration dates are not displaying.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.6.1
**WordPress Version -** 6.0.0
**Plugin Version -** 1.2.8
**Description -**

![image](https://user-images.githubusercontent.com/76723393/193192539-1f50fbfb-70ea-4068-9abe-2019171485f6.png)

**Comment by navneet-cedcoss** [comment]
Expiration date will come from pro plugin, will check in next update

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Okay
