### ISSUE TITLE
phpcs issues

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#150]
**Woo Commerce Version** - 7.2.3
**WordPress Version** - 6.1.1
**Plugin Version** - 1.4.0
**Description** - phpcs issues

[PHPcs.docx](https://github.com/wpswings/points-and-rewards-for-woocommerce/files/10399235/PHPcs.docx)

**Comment by navneet-cedcoss** [comment]
$WOOCS is a third party plugin variable not possible to fix this

**Comment by ashish-wps** [comment]
Okay 

[PHPcs.docx](https://github.com/wpswings/points-and-rewards-for-woocommerce/files/10425625/PHPcs.docx)
