### ISSUE TITLE
Use short code single time but output come twice

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#151]
**Woo Commerce Version** - 7.2.3
**WordPress Version** - 6.1.1
**Plugin Version** - 1.4.0
**Description** - Use short code single time but output come twice

![Screenshot at 2023-01-12 13-21-52](https://user-images.githubusercontent.com/105413021/212009382-4437f77f-4a01-4bc3-ad35-7e85624d98fe.png)

**Comment by navneet-cedcoss** [comment]
working fine

**Comment by ashish-wps** [comment]
Okay
