### ISSUE TITLE
Qa Issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#152]
**Woo Commerce Version** - 7.2.3
**WordPress Version** - 6.1.1
**Plugin Version** - 1.4.0
**Description** - Plugin version is not updated on line 67

![image](https://user-images.githubusercontent.com/105413021/212688173-a82a92f6-a63e-4a8a-8498-eec7189e90ee.png)

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
