### ISSUE TITLE
"User per post comment" feature issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#153]
**Woo Commerce Version** - 7.6.0
**WordPress Version** - 6.2
**Plugin Version** - 1.5.0
**Description** - "User per post comment" feature issue

https://user-images.githubusercontent.com/105413021/232026507-258887f9-e21d-4bd7-b8a5-eb1a093acd44.mp4

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
