### ISSUE TITLE
Commented code on line 1702

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#154]
Woo Commerce Version - 7.7.0
WordPress Version - 6.2.2
Plugin Version - 1.6.0
Description - Commented code on line 1702

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/9d291cef-d41e-487d-aaa3-9d500670d51f)

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
