### ISSUE TITLE
Point Log is not creating when admin reset points to a user

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#155]
Woo Commerce Version - 7.7.0
WordPress Version - 6.2.2
Plugin Version - 1.6.1
Description - Point Log is not creating when admin reset points to a user

https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/be007686-fe76-45b5-a833-6bf435e4f4be

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
