### ISSUE TITLE
Checkout page stuck on loading when user apply point

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#157]
**Woo Commerce Version** - 7.9.0
**WordPress Version** - 6.2.2
**Plugin Version** - 1.8.0
**Description** - Checkout page stuck on loading when user apply point
**Platform** - Local and Demo

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/63a182af-92d8-4291-927b-28d2cb61a207)

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
