### ISSUE TITLE
Available points switch into required points when user change currency 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#158]
**Woo Commerce Version** - 7.9.0
**WordPress Version** - 6.2.2
**Plugin Version** - 1.8.0
**Description** - Available points switch into required points when user change currency 

https://nimb.ws/AlQxMq

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
