### ISSUE TITLE
Admin can able to enter negative value in Segment Points and Font size option

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#161]
**Woo Commerce Version** - 8.0.2
**WordPress Version** - 6.3
**Plugin Version** - 1.9.0
**Description** - Admin can able to enter negative value in Segment Points and Font size option

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/1ced1b81-b2b0-4073-945a-dd9824a03580)

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
