### ISSUE TITLE
When user enter inappropriate value than it's show Saved Setting notification. 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#162]
Woo Commerce Version - 8.0.2
WordPress Version - 6.3
Plugin Version - 1.9.0
Description - When user enter inappropriate value than it's show Saved Setting notification. 
Note - Please add related pop-up message

https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/e647d0b9-2026-4340-82ff-d711cb26f7da

**Comment by navneet-cedcoss** [comment]
not possible to enter string in number field

**Comment by ashish-wps** [comment]
Fixed
