### ISSUE TITLE
 when user enter 0 in Segment Points, it's shows default value in Segment Points Table but user get 0

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#163]
Woo Commerce Version - 8.0.2
WordPress Version - 6.3
Plugin Version - 1.9.0
Description - when user enter 0 in Segment Points, it's shows default value in Segment Points Table but user get 0.

https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/d99868e2-d68f-4cd5-8519-b6865ffc8067

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
