### ISSUE TITLE
User can able to place order when admin deduct point while placing order

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#164]
**Woo Commerce Version** - 8.0.2
**WordPress Version** - 6.3
**Plugin Version** - 1.9.0
**Description** - User can able to place order when admin deduct point while placing order

https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/3909ab40-c01a-4d04-8a53-7a74ece1919a

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
