### ISSUE TITLE
can't able to open point log

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#165]
Woo Commerce Version - 8.0.2
WordPress Version - 6.3
Plugin Version - 1.9.0
Description - can't able to open point log

https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/e76b5575-3466-4153-a846-6758ae4082b4

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
