### ISSUE TITLE
image remove button is not available

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#167]
Woo Commerce Version - 8.1.1
WordPress Version - 6.3.1
Plugin Version - 2.0.0
Description - image remove button is not available

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/e927bd55-7bdb-404a-923d-e94c95b29640)

**Comment by navneet-cedcoss** [comment]
No need to provide a remove button, you can change the image.
This features need a image

**Comment by ashish-wps** [comment]
okay
