### ISSUE TITLE
Issue in Membership % discount option

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#168]
Woo Commerce Version - 8.1.1
WordPress Version - 6.3.1
Plugin Version - 2.0.0
Description - Issue in Membership % discount option

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/49115c74-1cc4-4d3e-9172-0c2ad7c6ce6a)

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/08bcb67c-bbc0-49c7-8a95-13e8ce17742c)

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
