### ISSUE TITLE
User able to enter negative value

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#169]
**Woo Commerce Version** - 8.1.1
**WordPress Version** - 6.3.1
**Plugin Version** - 2.0.0
**Description** - User able to enter negative value 

**Product Point** -

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/e42f87d6-d353-4be8-90fd-aaae0766c40a)

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/ed28e537-242d-45eb-b39d-eb3024ae4dbe)

**Conversion Point** -
![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/05f244ab-53d7-422f-9167-f1431b6d4377)

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/263b0b91-e1a5-4f1e-9221-adf05ff81392)

**Per Currency** - 

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/42e2a263-ef95-407a-9f98-792b0890a722)

**Order Total Point** -

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/3852524f-b981-4d60-a661-c1804e293362)

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
