### ISSUE TITLE
Please remove unnecessary pop-up when user did not win any badge  

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#170]
Woo Commerce Version - 8.1.1
WordPress Version - 6.3.1
Plugin Version - 2.0.0
Description - Please remove unnecessary pop-up when user did not win any badge  

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/0cbccbb4-d97f-4d59-bacf-2cf6a99b08fa)

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
