### ISSUE TITLE
Badge functionality is not working properly

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#171]
**Woo Commerce Version** - 8.1.1
**WordPress Version** - 6.3.1
**Plugin Version** - 2.0.0
**Description** - Badge functionality is not working properly when...
**Scenarios**  - When user create last badge with lesser amount according to the other badge Threshold Points..
> User get lesser amount badge and point

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/a012ea1f-266c-4faa-b8a9-9aa435f38f8b)

[scrnli_05_10_2023_11-46-50.webm](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/69660c9a-0763-4424-9b1c-a8c0dc8210a9)

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Okay
