### ISSUE TITLE
Order Rewards Settings is not working

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#172]
Woo Commerce Version - 8.2.1
WordPress Version - 6.3.2
Plugin Version - 2.0.1
Description - Order Rewards Settings is not working

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/12ff2466-6987-4762-bbda-58200d6f9ce8)

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/138d2895-9a93-46d9-a8e8-0a25893022ca)
