### ISSUE TITLE
Rewards Points type ( Percentage ) issue in membership setting

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#173]
Woo Commerce Version - 8.2.1
WordPress Version - 6.3.2
Plugin Version - 2.0.1
Description - Rewards Points type ( Percentage ) issue in membership setting

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/af343084-170e-4b11-9418-40fea17e21b8)

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/3b1082d3-1d39-4213-a151-624bfdaec09a)

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/8555bab3-79eb-4839-911b-82adda87a1bd)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
