### ISSUE TITLE
Restrict Points Notification didn't appear in Cart and Checkout Page Shortcode

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#174]
**Woo Commerce Version** - 8.2.1
WordPress Version - 6.3.2
**Plugin Version** - 2.0.1
**Description** - Restrict Points Notification didn't appear in Cart and Checkout Page Shortcode

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/4b806f43-b700-4ef7-ba8d-ec38afd11378)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed, it's only visible ob cart page.
