### ISSUE TITLE
When admin cancel the Membership plan than the point deduct from admin account

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#176]
Woo Commerce Version - 8.3.0
WordPress Version - 6.4.1
Plugin Version - 2.1.0
Description - When admin cancel the Membership plan than the point deduct from admin account

[scrnli_21_11_2023_12-59-53.webm](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/50bd0f5b-0975-4648-95da-d41c6f1211b5)

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Membership point didn't deduct when admin cancel membership.

**Comment by navneet-cedcoss** [comment]
fixed
