### ISSUE TITLE
Design Issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#179]
Woo Commerce Version - 8.3.1
WordPress Version - 6.4.1
Plugin Version - 2.0.1
Description - Design Issue

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/a7efc107-d0cb-43a4-85da-2eafa63d1969)

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/edaa488f-8dd7-49a3-808b-a554a94fbf92)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/f5992dae-4afb-4d30-80a3-f5eade3a9997)
