### ISSUE TITLE
ORG point Table and Order Total Point feature is not working because of PRO tag

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#181]
**Woo Commerce Version - 8.4.0
WordPress Version - 6.4.2
Plugin Version - 2.1.2
Description -** ORG point Table and Order Total Point feature is not working because of PRO tag

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/5faa3ddc-aed0-45f0-a6c6-069393ef5112)

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/2dae90ab-98a6-45a0-975e-449938fa0938)

**Comment by navneet-cedcoss** [comment]
fixed
