### ISSUE TITLE
ORG plugin Point Notification and membership features are showing pro tag

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#182]
**Woo Commerce Version - 8.4.0
WordPress Version - 6.4.2
Plugin Version - 2.1.2
Description -** ORG plugin Point Notification, Badges and membership features are showing pro tag

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/9bb599f7-41b8-4b42-9d47-3c80fdb9a6b9)

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/031d3acb-24b7-4449-aa4d-0268a23a380c)

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/f594908a-0ed6-4f6d-bcac-e7d35303e067)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
