### ISSUE TITLE
Apply Points on Checkout feature is not working

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#183]
**Woo Commerce Version - 8.4.0
WordPress Version - 6.4.2
Plugin Version - 2.1.2
Description -** Apply Points on Checkout feature is not working

[scrnli_11_01_2024_11-31-46.webm](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/aa5254b0-e159-48e2-ad6d-ab9e9cbd8f7e)

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed

**Comment by Joehoel** [comment]
How did you fix this?
