### ISSUE TITLE
Thank u short code is not working

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#185]
**Woo Commerce Version - 8.5.2
WordPress Version - 6.4.3
Plugin Version - 2.1.2
Description -** Thank u short code is not working

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/cd8c4757-00f2-4e1b-8b72-3d1ac917609d)

**Comment by navneet-cedcoss** [comment]
![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/79437875/810b688c-67f5-448a-9bea-debb26011802)
Fixed

**Comment by ashish-wps** [comment]
Fixed
