### ISSUE TITLE
User should pay decimal amount on cart and checkout 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#186]
**Woo Commerce Version - 8.5.2
WordPress Version - 6.4.3
Plugin Version - 2.1.2
Description -** User should pay decimal amount on cart and checkout 

[scrnli_12_02_2024_11-56-26.webm](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/c43d859c-46e3-49a3-9215-bce54ca4563d)

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
