### ISSUE TITLE
Check mark is showing after membership expire and renewal option in not available

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#188]
**Woo Commerce Version - 8.5.2
WordPress Version - 6.4.3
Plugin Version - 2.1.2
Description -** Check mark is showing after membership expire and renewal option in not available

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/73687389-f23b-413a-87f6-628d2e5903ad)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
