### ISSUE TITLE
View Log option is not working in admin panel 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#191]
**Woo Commerce Version - 8.6.1
WordPress Version - 6.4.3
Plugin Version - 2.2.0
Description -** View Log option is not working in admin panel 

[scrnli_18_03_2024_13-36-21.webm](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/e792b074-ff8d-4db5-bb69-4df7c56dd849)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
