### ISSUE TITLE
Insufficient Point notification is not visible when user enter more then existing point

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#192]
**Woo Commerce Version - 8.6.1
WordPress Version - 6.4.3
Plugin Version - 2.2.0
Description -**  Insufficient Point notification is not visible when user enter more then existing point

[scrnli_18_03_2024_13-40-39.webm](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/2226f3c6-be7e-4981-830f-8338560eabfe)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/6c1ab500-fd20-41ca-b929-7c748d2797fe)
