### ISSUE TITLE
Restrict Points Message option is not working

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#193]
**Woo Commerce Version - 8.6.1
WordPress Version - 6.4.3
Plugin Version - 2.2.0
Description -**  Restrict Points Message option is not working

[scrnli_18_03_2024_15-10-30.webm](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/038f9b76-2e82-4c84-9875-d00a728bd40e)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/378cf9c7-808a-4ed8-9aba-cfda7e20fa2e)
