### ISSUE TITLE
Purchase through Points feature is not working with variable product when user have a membership

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#194]
**Woo Commerce Version - 8.6.1
WordPress Version - 6.4.3
Plugin Version - 2.2.0
Description -** Purchase through Points feature is not working with variable product when user have a membership

[scrnli_18_03_2024_16-28-01.webm](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/8c013c67-b149-4d17-8400-ad623ebef9a9)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
