### ISSUE TITLE
Content issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#197]
**Woo Commerce Version - 8.8.2
WordPress Version - 6.5.2
Plugin Version - 2.3.0
Description -** Content issue
**Suggestion -** Make New Layout heading as "Point Tab Layout setting"

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/5fc1cd43-ca0c-4689-97fd-fe5af3dd648b)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
fixed
