### ISSUE TITLE
Uncaught Error on client site

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#200]
**Woo Commerce Version - 8.9.1
WordPress Version - 6.5.3
Plugin Version - 2.3.1
Description -** Uncaught Error on client site

Uncaught Error: Call to a member function get_price() on bool in /srv/htdocs/wp-content/plugins/points-and-rewards-for-woocommerce/public/class-points-rewards-for-woocommerce-public.php:2707

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
