### ISSUE TITLE
Point should update when user click on update button

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#201]
**Woo Commerce Version - 8.9.2
WordPress Version - 6.5.4
Plugin Version - 2.3.2
Description -** Point should update when user click on update button

[scrnli_10_06_2024_11-00-55.webm](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/984a69d8-1a55-4228-b773-ac7dbe7496c1)

**Comment by navneet-cedcoss** [comment]
working fine

**Comment by ashish-wps** [comment]
Okay
