### ISSUE TITLE
Please show Total point on cart page

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#203]
**Woo Commerce Version - 9.1.4
WordPress Version - 6.6.1
Plugin Version - 2.4.1
Description -** Please show Total point on cart page

![image](https://github.com/user-attachments/assets/c9631b86-4360-4880-a2bf-dcbc3bf60405)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
