### ISSUE TITLE
Email social link is not working

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#204]
**Woo Commerce Version - 9.2.3
WordPress Version - 6.6.1
Plugin Version - 2.4.2
Description -** Email social link is not working

![image](https://github.com/user-attachments/assets/c4afa8a6-35bf-420d-8954-8aaf4a898681)

**Comment by navneet-cedcoss** [comment]
Checked and verified on both the old and new sites, and it is working fine.

**Comment by ashish-wps** [comment]
Okay
