### ISSUE TITLE
Can't able to save setting due to WC validation 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#205]
**Woo Commerce Version - 9.2.3
WordPress Version - 6.6.1
Plugin Version - 2.4.2
Description -** Can't able to save setting due to WC validation 

![image](https://github.com/user-attachments/assets/0caf27c3-d74d-4042-b96d-1bab8cb34c09)
![image](https://github.com/user-attachments/assets/bc0dfc87-4013-4eed-ab3c-b49ade00dea2)
![image](https://github.com/user-attachments/assets/b7db86f3-2fa5-4848-985c-2ff4df89bda8)
![image](https://github.com/user-attachments/assets/1866697f-d93f-4115-acfc-a583fe25f62c)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
