### ISSUE TITLE
Point type option appears twice in the selection menu.

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#206]
**Woo Commerce Version - 9.3.3
WordPress Version - 6.6.2
Plugin Version - 2.5.2
Description -** Point type option appears twice in the selection menu.

![image](https://github.com/user-attachments/assets/160d6145-65df-4b99-85d7-ced0679f350a)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
fixed
