### ISSUE TITLE
phpcs issues

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#208]
**Woo Commerce Version - 9.3.3
WordPress Version - 6.6.2
Plugin Version - 2.5.2
Description -** phpcs issues

**ORG -**
[PHPcs.docx](https://github.com/user-attachments/files/17702322/PHPcs.docx)

**PRO-**
[PHPcs.docx](https://github.com/user-attachments/files/17702329/PHPcs.docx)

**Comment by navneet-cedcoss** [comment]
A few issues are not fixable, but all other issues have been resolved

**Comment by ashish-wps** [comment]
Fixed
