### ISSUE TITLE
The discount is not loaded after clicking APPLY POINTS in the checkout page

### ISSUE THREAD

**Issue by Anatal** [wpswings/points-and-rewards-for-woocommerce#209]
After clicking the APPLY POINTS button on the cart page, the discount is not refreshed unless I refresh the page myself.
![image](https://github.com/user-attachments/assets/a5f0b78b-ed61-479d-afcc-742010b3a2ff)

**Comment by WP-Swings** [comment]
Hello,

Thank you for using our plugin!

In reference to your issue, it seems there is some conflict with third party plugin which is restricting the page reload as the page gets reloaded once you enter points and click on "Apply Points" button so please run a test by deactivating all third-party plugin except woo-commerce and our points plugin and then check

Regards

**Comment by Anatal** [comment]
I disabled all plugins except 4 because without them the website breaks. It still doesn't solve the problem I mentioned above.
![image](https://github.com/user-attachments/assets/18bff113-0c48-4b2c-824b-394ba9d014ef)
